### PR TITLE
react-clock solution ver.1

### PR DESCRIPTION
**Pull request by viacheslav-saprykin**
[DemoLink](viacheslav-saprykin.github.io/react_clock)

### CODE REVIEW

**Review by polosanya — COMMENTED** [review]
Reopen the pull request if you want it to be reviewed)
Feel free to ask for help if fe_chat if you have any difficulties

**Review by TarasHoliuk — COMMENTED** [review]
Please, reopen PR

**Review by OleziO — COMMENTED** [review]
Open PR

**Review by OleziO — COMMENTED** [review]
.

**Comment by viacheslav-saprykin** [comment]
Hi! 
Good afternoon! I immediately realized that something was wrong with this PR and tried to close and delete it. I immediately created a new on
[PR](https://github.com/mate-academy/react_clock/pull/1564)

**Review by sTorba24 — COMMENTED** [review]
Reopen this PR, i see that you closed second too

**Pull request closed without merging**
